name: $(date:yyyyMMdd)$(rev:.rr) #20191214.10

trigger:
  - master


stages:
  - stage: compile
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build ./Translator.sln
  - stage: test
    jobs:
      - job: aspnet_test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test ./Translator.sln --logger trx --collect:"XPlat Code Coverage"
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: cobertura
              summaryFileLocation: '**/coverage.cobertura.xml'
  - stage: analyze
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '3.1.100'
          - script: dotnet tool install --global dotnet-sonarscanner
          - script: |
              dotnet sonarscanner begin \
              /k:ccc-translator \
              /d:sonar.login=$SONAR_TOKEN \
              /d:sonar.host.url=https://sonarcloud.io/ \
              /d:sonar.cs.operator.reportsPaths=**/TestResults/*/coverage.cobertura.xml \
              /d:sonar.cs.vstest.reportsPaths=**/*.trx \
              /o:ccc-p2
              dotnet build ./Translator.sln
              dotnet test ./Translator.sln --logger trx
              dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
            env:
              SONAR_TOKEN: $(SONAR_LOGIN)

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: docker image build -f ./dockerfile -t cccp2/translator:$BUILD_NAME .
            env:
              BUILD_NAME: $(Build.DefinitionName)
          - script: docker login --username $DOCKER_USER --password $DOCKER_TOKEN
            env:
              DOCKER_TOKEN: $(docker.token)
              DOCKER_USER: $(docker.user)
          - script: docker image push cccp2/translator:$BUILD_NAME
            env:
              BUILD_NAME: $(Build.DefinitionName)