// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Translator.Storing;

namespace Translator.Storing.Migrations
{
    [DbContext(typeof(TranslatorDbContext))]
    partial class TranslatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Translator.Storing.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("MessageDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Content = "first message",
                            MessageDateTime = new DateTime(2019, 12, 15, 14, 23, 20, 761, DateTimeKind.Local).AddTicks(597),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 2,
                            Content = "second message",
                            MessageDateTime = new DateTime(2019, 12, 15, 14, 23, 20, 765, DateTimeKind.Local).AddTicks(7987),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            Content = "third message",
                            MessageDateTime = new DateTime(2019, 12, 15, 14, 23, 20, 765, DateTimeKind.Local).AddTicks(8112),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Translator.Storing.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Language = "spanish",
                            Password = "12345678",
                            Username = "sergio"
                        },
                        new
                        {
                            UserId = 2,
                            Language = "english",
                            Password = "12345678",
                            Username = "john"
                        },
                        new
                        {
                            UserId = 3,
                            Language = "french",
                            Password = "12345678",
                            Username = "herman"
                        });
                });

            modelBuilder.Entity("Translator.Storing.Models.Message", b =>
                {
                    b.HasOne("Translator.Storing.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
